<?php
namespace Isync\Demo\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('setting')->insert([
            [
                'vName' => 'COMPANY_NAME',
                'vDesc' => 'Company Name',
                'vValue' => NULL,
                'iSettingOrder' => 1,
                'eConfigType' => 'Company',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_EMAIL',
                'vDesc' => 'Company Email ID',
                'vValue' => NULL,
                'iSettingOrder' => 2,
                'eConfigType' => 'Company',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_ADDRESS',
                'vDesc' => 'Company address',
                'vValue' => NULL,
                'iSettingOrder' => 3,
                'eConfigType' => 'Company',
                'eDisplayType' => 'textarea',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_DESC',
                'vDesc' => 'Company Description',
                'vValue' => NULL,
                'iSettingOrder' => 4,
                'eConfigType' => 'Company',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_NUMBER',
                'vDesc' => 'Company Number',
                'vValue' => '+44 (0) 1236 729 494',
                'iSettingOrder' => 5,
                'eConfigType' => 'Company',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_LOGO',
                'vDesc' => 'Company Logo',
                'vValue' => NULL,
                'iSettingOrder' => 6,
                'eConfigType' => 'Company',
                'eDisplayType' => 'file',
                'vSourceValue' => '{"FILE_EXT":"","FILE_SIZE":"500"}',
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_FAVICON',
                'vDesc' => 'Company Favicon',
                'vValue' => NULL,
                'iSettingOrder' => 7,
                'eConfigType' => 'Company',
                'eDisplayType' => 'file',
                'vSourceValue' => '{"FILE_EXT":"","FILE_SIZE":"500"}',
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_FOOTER_LOGO',
                'vDesc' => 'Company Footer Logo',
                'vValue' => NULL,
                'iSettingOrder' => 8,
                'eConfigType' => 'Company',
                'eDisplayType' => 'file',
                'vSourceValue' => '{"FILE_EXT":"","FILE_SIZE":"500"}',
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_WEBSITE',
                'vDesc' => 'Company Website',
                'vValue' => NULL,
                'iSettingOrder' => 9,
                'eConfigType' => 'Company',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Inactive',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COPYRIGHTED_TEXT',
                'vDesc' => 'Copyright text',
                'vValue' => NULL,
                'iSettingOrder' => 10,
                'eConfigType' => 'Company',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'FOOTER_DESCRIPTION',
                'vDesc' => 'Footer Description',
                'vValue' => NULL,
                'iSettingOrder' => 11,
                'eConfigType' => 'Company',
                'eDisplayType' => 'textarea',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'COMPANY_BANNER_LOGO',
                'vDesc' => 'Company Banner Logo',
                'vValue' => NULL,
                'iSettingOrder' => 12,
                'eConfigType' => 'Company',
                'eDisplayType' => 'file',
                'vSourceValue' => '{"FILE_EXT":"","FILE_SIZE":"500"}',
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'ADMIN_EMAIL',
                'vDesc' => 'Administrator Email Address',
                'vValue' => NULL,
                'iSettingOrder' => 1,
                'eConfigType' => 'Email',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'EMAIL_PROTOCOL',
                'vDesc' => 'Email Protocol',
                'vValue' => NULL,
                'iSettingOrder' => 2,
                'eConfigType' => 'Email',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SMTP_HOST',
                'vDesc' => 'SMTP Server Host',
                'vValue' => NULL,
                'iSettingOrder' => 3,
                'eConfigType' => 'Email',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SMTP_PASS',
                'vDesc' => 'SMTP Server Password',
                'vValue' => NULL,
                'iSettingOrder' => 4,
                'eConfigType' => 'Email',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SMTP_PORT',
                'vDesc' => 'SMTP Server Port',
                'vValue' => NULL,
                'iSettingOrder' => 5,
                'eConfigType' => 'Email',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SMTP_USERNAME',
                'vDesc' => 'SMTP Server User name',
                'vValue' => NULL,
                'iSettingOrder' => 6,
                'eConfigType' => 'Email',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_FACEBOOK',
                'vDesc' => 'Facebook URL',
                'vValue' => 'https://www.facebook.com/',
                'iSettingOrder' => 1,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_GOOGLE_PLUS',
                'vDesc' => 'Google Plus URL',
                'vValue' => 'https://plus.google.com',
                'iSettingOrder' => 2,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Inactive',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_INSTAGRAM',
                'vDesc' => 'Instagram URL',
                'vValue' => 'https://www.instagram.com/',
                'iSettingOrder' => 3,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_LINKEDIN',
                'vDesc' => 'Linkedin URL',
                'vValue' => 'https://linkedin.com',
                'iSettingOrder' => 4,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_YOUTUBE',
                'vDesc' => 'Youtube URL',
                'vValue' => 'https://youtube.com',
                'iSettingOrder' => 5,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_WHATSAPP',
                'vDesc' => 'Whatsapp URL',
                'vValue' => 'https://whatsapp.com',
                'iSettingOrder' => 6,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_TWITTER',
                'vDesc' => 'Twitter URL',
                'vValue' => 'https://www.twitter.com/',
                'iSettingOrder' => 7,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'SOCIAL_PINTEREST',
                'vDesc' => 'Pinterest URL',
                'vValue' => 'https://www.pinterest.com/',
                'iSettingOrder' => 8,
                'eConfigType' => 'Social',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'GOOGLE_CAPTCHA_SITE_KEY',
                'vDesc' => 'Google Captcha Site Key',
                'vValue' => '6LeYe08pAAAAAPJnjWVDU47L949QpyoidOH1PkZO',
                'iSettingOrder' => 1,
                'eConfigType' => 'Config',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Inactive',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'GOOGLE_CAPTCHA_SECRET_KEY',
                'vDesc' => 'Google Captcha Secret Key',
                'vValue' => '6LeYe08pAAAAAO_qj_5hgfdKDFgfji5B3wF9cMK1',
                'iSettingOrder' => 2,
                'eConfigType' => 'Config',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Inactive',
                'dtAddedDate' => now(),
            ],
            [
                'vName' => 'ENABLE_LOGO',
                'vDesc' => 'Enable Logo Display',
                'vValue' => '1',
                'iSettingOrder' => 1,
                'eConfigType' => 'Config',
                'eDisplayType' => 'text',
                'vSourceValue' => NULL,
                'eStatus' => 'Active',
                'dtAddedDate' => now(),
            ],
        ]);
    }
}
